spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5432/user-server
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST2}
    port: ${RABBITMQ_PORT2}
    username: ${RABBITMQ_USERNAME2}
    password: ${RABBITMQ_PASSWORD2}
    virtual-host: ${RABBITMQ_VHOST2}
    ssl:
      enabled: true


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081