
spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5432/user-server
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  server:
    port: 8081