spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5432/user-server
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5670}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    ssl:
      enabled: ${RABBITMQ_SSL:true}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081